apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: artist-api
  description: Retrieve artist details
spec:
  type: openapi
  lifecycle: production
  owner: artist-relations-team
  system: artist-engagement-portal
  definition: |
    openapi: "3.0.0"
    info:
      version: 1.0.0
      title: Artist API
      license:
        name: MIT
    servers:
      - url: http://artist.spotify.net/v1
    paths:
      /artists:
        get:
          tags:
            - Device
          description: returns all registered devices
          operationId: getDevices
          parameters:
            - in: query
              name: skip
              description: number of records to skip
              schema:
                type: integer
                format: int32
            - in: query
              name: limit
              description: max number of records to return
              schema:
                type: integer
                format: int32
          responses:
            '200':
              description: All the devices
              content:
                application/json:
                  schema:
                    type: array
                    items:
                      type: string
                      format: uri
                      example: 'http://10.0.0.225:8080'
